HW_code/RPI/flaskapp/auth.py
"""Routes for user authentication."""
from flask import current_app as app
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import current_user, login_user, logout_user

from . import login_manager
from .assets import compile_auth_assets
from .backend.mainflux_provisioning import register_node_backend
from .control import sign_up_database, validate_user, delete_tables_entries, validate_email, send_email, get_mainflux_token
from .forms import LoginForm, SignupForm, ResetForm, PasswordResetForm
from .models import db, User
from config import ConfigFlaskApp 
import urllib3
import requests
import bcrypt

if app.config['HTTPS_ENABLED']:
    host = ConfigFlaskApp.SSL_SERVER_URL
    ssl_flag = ConfigFlaskApp.SSL_CA_LOCATION 
else:
    host = ConfigFlaskApp.SERVER_URL
    ssl_flag = False 
# Blueprint Configuration
auth_bp = Blueprint('auth_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_auth_assets(app)


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.

    GET: Serve sign-up page.
    POST: If submitted credentials are valid:
    add user to 'userdata' table at db,
    initialize 'nodeconfig' table at db,
    create 'tokens' table at db;
    redirect user to the logged-in node configuration page.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))  # Bypass if user is logged in

    signup_form = SignupForm()
    if request.method == 'POST' and signup_form.validate_on_submit():
        # Initialize user and all associated tables in db in RPI
        error_msg, user, node_id = sign_up_database(signup_form.name.data, #deleted organization from form; org=email
                                                    signup_form.email.data,
                                                    signup_form.password.data,
                                                    signup_form.device.data)
        if not error_msg:
            login_user(user)  # Log in as newly created user (first, to allow queries using current_user)
            # User data provisioning to backend
            error_msg = register_node_backend(signup_form.name.data, #deleted organization from form; org=email
                                              signup_form.email.data,
                                              signup_form.password.data,
                                              node_id)
            if not error_msg:
                # Registration OK, app log in and proceed
                return redirect(url_for('main_bp.dashboard'))
            logout_user()
            delete_tables_entries()

        flash(error_msg)
        return redirect(url_for('auth_bp.signup'))

    flash("This registration procedure will link the node to the account provided. A new account will be created "
          "if you don't have one.")
    return render_template('signup.jinja2',
                           title='Create account - ADO',
                           form=signup_form,
                           template='signup-page',
                           body="Sign up for a user account.")


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    User login page.

    GET: Serve Log-in page.
    POST: If form is valid and new user creation succeeds, redirect user to the logged-in homepage.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))  # Bypass if user is logged in

    login_form = LoginForm()
    if request.method == 'POST' and login_form.validate_on_submit():
        # Validate user
        user = validate_user(login_form.email.data,
                             login_form.password.data)
        if user:
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.dashboard'))
        flash('Invalid email/password combination.')
        return redirect(url_for('auth_bp.login'))

    return render_template('login.jinja2',
                           form=login_form,
                           title='Log in - ADO',
                           template='login-page')

@auth_bp.route('/forgotpassword', methods=['GET', 'POST'])
def forgotpassword():
    """
    User reset password.

    GET: Serve password reset page where user submits their email.
    POST: If form is valid and email checks, send user a password reset url.
    """
    pass_reset_form = ResetForm()
    if request.method == 'POST' and pass_reset_form.validate_on_submit():
        # Validate user
        user = validate_email(pass_reset_form.email.data)
        if user:
            status= send_email(user)
            if status == 'success':
                flash("An email with the reset link has been sent to this email address. You should receive it shortly")
                return redirect(url_for('auth_bp.login'))
            else:
                flash("A problem occured while trying to send a password reset email.")
                return redirect(url_for('auth_bp.forgotpassword'))

        flash('This node is registered to a different email address')
        #return redirect(url_for('auth_bp.login'))
        return redirect(url_for('auth_bp.forgotpassword'))

    return render_template('forgot.jinja2',
                           form=pass_reset_form,
                           title='Password Reset - ADO',
                           template='login-page')

@auth_bp.route('/password_reset_code/<token>', methods=['GET', 'POST'])
def pass_reset_code(token):
    """
    User reset password.

    GET: Serve password reset page.
    POST: If form is valid and new password checks, store the new password and redirect to login.
    """
    user = User.verify_reset_token(token)
    if not user:
        print('no user found')
        flash('User not found or token has expired')
        return redirect(url_for('auth_bp.login'))

    pass_reset_form = PasswordResetForm()
    if request.method == 'POST' and pass_reset_form.validate_on_submit():
        #sending the new (hashed) password to user-control, together with a new, short-lived, token:
        new_token, identifier= get_mainflux_token(user)
        new_password= pass_reset_form.password.data.encode('utf-8')
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        #request post to user-control to modify password in database
        url = host + '/control/RenewAccountPassword/'+str(new_token)+"/"+ str(identifier)
        data = {
            "change": bcrypt.hashpw(new_password, bcrypt.gensalt(10)) #new password for the encoded email
        }
        headers = {"Content-Type": 'application/json'}
        response = requests.post(url, json=data, headers=headers, verify= ssl_flag) #verify= false disables ssl check
        print("*********response**********",response)
        status = response.json()['status']
        print(status)

        # verify if change was made with success
        if status == "success":
            user.set_password(pass_reset_form.password.data, hash_it=app.config['HASH_USER_PASSWORD'])
            db.session.commit()
            flash('Password successfully updated')
            return redirect(url_for('auth_bp.login'))
        else:
            flash('Password was not updated, please try again later')
            return redirect(url_for('auth_bp.login'))
    return render_template('reset_verified.jinja2', form= pass_reset_form, title= "Reset Password - ADO", template='login-page')


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view the page.')
    return redirect(url_for('auth_bp.login'))

HW_code/RPI/flaskapp/routes.py
"""Logged-in page routes."""
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask import current_app as app
from flask_login import login_required, logout_user

from .assets import compile_main_assets
from .control import get_node_id, get_thing_id, get_account_token, get_config_obj, delete_tables_entries, update_config_values, get_wifi_obj, \
    update_wifi_data, get_user_org, get_tokens_obj, get_calib_1_obj, get_calib_2_obj, get_req_calib_1_obj, get_req_calib_2_obj
from .forms import WifiForm
from flaskapp.backend.grafana_bootstrap import load_json
from flaskapp.backend.mainflux_provisioning import delete_thing
from config import ConfigFlaskApp
import requests
if app.config['HTTPS_ENABLED']:
    host = ConfigFlaskApp.SSL_SERVER_URL
    ssl_flag = ConfigFlaskApp.SSL_CA_LOCATION 
else:
    host = ConfigFlaskApp.SERVER_URL
    ssl_flag = False


# Blueprint Configuration
main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_main_assets(app)

@main_bp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard():
    """
    Node configuration page.
    GET:
    Show active sensors from database, allow enable/disable sensors, show menu options.
    """
    global tokens, client, mqtt_topic, MQTT_CONNECTED, MQTT_SUBSCRIBED

    str_current_config = ['checked' if sensor_sr != 0 else '' for sensor_sr in get_config_obj().get_values()]
    # str list of 'checked' if sensor sampling rate is not 0 else '' (checked is passed to html checkbox)

    return render_template('dashboard.jinja2',
                           title='Configuration - ADO',
                           template='dashboard-template',
                           node_id=get_node_id(),
                           s01_state=str_current_config[0],
                           s02_state=str_current_config[1],
                           s03_state=str_current_config[2],
                           s04_state=str_current_config[3],
                           s05_state=str_current_config[4],
                           s06_state=str_current_config[5],
                           s07_state=str_current_config[6],
                           s08_state=str_current_config[7],
                           s09_state=str_current_config[8],
                           s10_state=str_current_config[9],
                           s11_state=str_current_config[10])


@main_bp.route('/wifi', methods=['GET', 'POST'])
@login_required
def set_wifi():
    """
    Wifi configuration page.

    GET: Serve Set-wifi page and show current SSID stored.
    POST: If form is valid, add new wifi data (delete previous), show success message.
    """
    wifi_form = WifiForm()

    if get_wifi_obj().active:
        current_wifi_state = 'checked'  # Get current wifi status to be displayed in page
    else:
        current_wifi_state = ''

    if request.method == 'POST' and wifi_form.validate_on_submit():
        # Store Wifi details
        update_wifi_data(wifi_form.ssid.data,
                         wifi_form.password.data)
        flash('New SSID and password stored.')
        return redirect(url_for('main_bp.set_wifi'))

    return render_template('wifi.jinja2',
                           form=wifi_form,
                           title='Configure WiFi - ADO',
                           template='wifi-page',
                           current_ssid=get_wifi_obj().ssid,
                           current_wifi_state=current_wifi_state)


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out."""
    logout_user()
    return redirect(url_for('auth_bp.login'))


@main_bp.route("/delete")
@login_required
def delete():
    """Factory reset. Delete thing from mainflux. Leave account alive. Delete entries one by one from each table"""
    token = get_account_token()
    thingid= get_thing_id() #not name!!! mainflux thing id. get_node_id returns name
    response = delete_thing(token, thingid)
    if response.ok:
      delete_tables_entries()
      logout_user()
    else:
      flash("Error when trying to factory reset. Please try again after loging in.")
    return redirect(url_for('main_bp.dashboard'))



@main_bp.route('/activatewifi', methods=['POST'])
@login_required
def get_post_js_data_activatewifi():
    """Receives post message from js on-off button to activate wifi."""
    jsdata = request.form['javascript_data']
    if jsdata == 'true':
        activate = 1
    elif jsdata == 'false':
        activate = 0
    else:
        activate = None
    update_wifi_data(activate=activate)
    return jsdata


@main_bp.route('/setsensor', methods=['POST'])
@login_required
def get_post_js_data_setsensor():
    """Receives post message from js on-off button, activates SPECIFIC sensor to default sampling rate."""
    str_sensor_num = request.form['sensor_num']  # Data from js
    state = request.form['box_state']

    sensor_idx = int(str_sensor_num[-2:]) - 1
    new_value = app.config['DEFAULT_SR'] if state == 'true' else 0

    # update rpi db
    update_config_values(sensor_idx, new_value)
    return state

@main_bp.route('/upgrade', methods=['GET','POST'])
@login_required
def dashboard_upgrade():

  try:
    organization = get_user_org() 
    url = host + '/control/grafana/dash_update'
    data = {
      "organization": str(organization)
    }
    headers = {"Content-Type": 'application/json'}
    status= requests.post(url, json=data, headers=headers, verify=ssl_flag)
    print("*****received answer is:", status.json())
    if status.json()['status'] == 'success':
      flash('Dashboard has been upgraded to the last version')
    else:
      flash(str(status.json()['status']))
  except:
      flash('Something went wrong, Try again later')
  return redirect(url_for('auth_bp.login'))
    

HW_code/RPI/flaskapp/templates/dashboard.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
    {#    <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">#}
{% endblock %}

{% block content %}

    {% if current_user.is_authenticated %}

        <h1 style="margin-top: 80px">Node Configuration</h1>
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
        {% endfor %}
        
        <p style="border-bottom: 1px solid lightblue; margin-bottom: 1px">This node is linked to: {{ current_user.email }}</p>

        <div class="row" style="margin-top: 30px; margin-bottom: 30px">
            <div class="column">
                <p style="font-size: 1rem">Node name: {{ node_id }}</p>
                <img src="{{ url_for('static', filename='dist/img/node.png') }}">
            </div>
            <div class="column">
                <p style="font-size: 1rem">Check active sensors:</p>

{#                https://github.com/BaseMax/CustomWebCheckbox#}
                <label class="checkbox_container" style="text-align: start">
                    Temperature-S
                    <input type="checkbox" name="boxs01" id="s01" onclick="sendEvent('s01')" {{ s01_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>
                
                <label class="checkbox_container" style="text-align: start">
                    Temperature-D
                    <input type="checkbox" name="boxs11" id="s11" onclick="sendEvent('s11')" {{ s11_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>
                
                <label class="checkbox_container">
                    Humidity
                    <input type="checkbox" name="boxs02" id="s02" onclick="sendEvent('s02')" {{ s02_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    pH
                    <input type="checkbox" name="boxs03" id="s03" onclick="sendEvent('s03')" {{ s03_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Turbidity
                    <input type="checkbox" name="boxs04" id="s04" onclick="sendEvent('s04')" {{ s04_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Conductivity 1-15 ms/cm
                    <input type="checkbox" name="boxs05" id="s05" onclick="sendEvent('s05')" {{ s05_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Conductivity 10-100 ms/cm
                    <input type="checkbox" name="boxs06" id="s06" onclick="sendEvent('s06')" {{ s06_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Atmospheric Temp
                    <input type="checkbox" name="boxs07" id="s07" onclick="sendEvent('s07')" {{ s07_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Oxygen
                    <input type="checkbox" name="boxs08" id="s08" onclick="sendEvent('s08')" {{ s08_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Water Level
                    <input type="checkbox" name="boxs09" id="s09" onclick="sendEvent('s09')" {{ s09_state }}>
                    <span class="checkbox_mark"></span>
                </label>
                <br>

                <label class="checkbox_container">
                    Air CO2
                    <input type="checkbox" name="boxs10" id="s10" onclick="sendEvent('s10')" {{ s10_state }}>
                    <span class="checkbox_mark"></span>
                </label>  </div>
            
                
        </div>

        <p style="border-bottom: 1px solid lightblue;"></p>

        <a href="{{ url_for('main_bp.set_wifi') }}" style="margin-top: auto">Configure WiFi</a>
        {#        <p style="opacity: .6; display: inline-block"> - </p>#}
        <a style="margin-top: auto">-</a>
        <a href="{{ url_for('main_bp.dashboard_upgrade') }}" style="margin-top: auto">Upgrade Dashboard</a>
        <a style="margin-top: auto">-</a>
        <a href="{{ url_for('main_bp.dashboard') }}" style="margin-top: auto">Refresh Page</a>
        <a style="margin-top: auto">-</a>
        <a href="{{ url_for('main_bp.delete') }}" style="margin-top: auto">Factory Reset</a>
        <a style="margin-top: auto">-</a>
        <a href="{{ url_for('main_bp.logout') }}" style="margin-top: auto; margin-bottom: 20px">Log out</a>

    {% endif %}

{% endblock %}

{% block additionalscripts %}
    <script>
        function sendEvent(boxid) {
            var checkbox = document.getElementById(boxid);
            if (checkbox.checked == true) {
                $.post( "/setsensor", {box_state: checkbox.checked, sensor_num: boxid});
            } else {
                $.post( "/setsensor", {box_state: checkbox.checked, sensor_num: boxid});
            }
        }
    </script>
{% endblock %}

HW_code/RPI/flaskapp/templates/forgot.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

    <div class="formwrapper">
        <h1> Reset password </h1>
        <p> Enter your information to obtain a password reset link</p>
        
        <form method="POST">
            {{ form.csrf_token() }}

            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}

            <fieldset class="email">
                {{ form.email.label }}
                {{ form.email(placeholder='youremail@example.com') }}
                {% if form.email.errors %}
                    <ul class="errors">
                        {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <div class="submitbutton">
                <input id="submit" type="submit" value="Send Reset Email">
            </div>

            <div class="loginsignup">
                <span><a href="{{ url_for('auth_bp.login') }}">Back to Login.</a></span>
            </div>
        </form>
    </div>
{% endblock %}

HW_code/RPI/flaskapp/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{{title}}</title>
    <meta name="HandheldFriendly" content="True" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="theme-color" content="#5eb9d7" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='dist/img/logo.png') }}" type="image/x-icon"/>
    {% block pagestyles %}{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
</head>

<body class="{{template}}">
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>

    {% block additionalscripts %}{% endblock %}
</body>

</html>

HW_code/RPI/flaskapp/templates/login.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class="formwrapper">
        <form method="POST">
            {{ form.csrf_token() }}

            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}

            <fieldset class="email">
                {{ form.email.label }}
                {{ form.email(placeholder='youremail@example.com') }}
                {% if form.email.errors %}
                    <ul class="errors">
                        {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="password">
                {{ form.password.label }}
                {{ form.password }}
                {% if form.password.errors %}
                    <ul class="errors">
                        {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <div class="submitbutton">
                <input id="submit" type="submit" value="Log In">
            </div>

            <div class="loginsignup">
                <span>Haven't registered this node yet? <a href="{{ url_for('auth_bp.signup') }}">Register.</a></span>
            </div>
        </form>
    </div>
{% endblock %}

HW_code/RPI/flaskapp/templates/reset_email.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

    <div class="formwrapper">
        <h1> Hi {{ name }}, </h1>
        <h2> To reset your  ADO-node password, please click the following link within 1 hour. </h2>
        <a href="{{ url_for('auth_bp.pass_reset_code', token=token, _external=True) }}" style="content:attr(href);"> Reset Password</a>
        <h2> Not working? Try copying and pasting it into your browser.</h2>
        
    </div>
{% endblock %}

HW_code/RPI/flaskapp/templates/reset_verified.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

    <div class="formwrapper">
        <h1> Enter your new password </h1>
        
        <form method="POST">
            {{ form.csrf_token() }}

            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}

            <fieldset class="password">
                {{ form.password.label }}
                {{ form.password }}
                {% if form.password.errors %}
                    <ul class="errors">
                        {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="confirm">
                {{ form.confirm.label }}
                {{ form.confirm }}
                {% if form.confirm.errors %}
                    <ul class="errors">
                        {% for error in form.confirm.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <div class="submitbutton">
                <input id="submit" type="submit" value="Set New Password">
            </div>

            <div class="loginsignup">
                <span><a href="{{ url_for('auth_bp.login') }}">Back to Login.</a></span>
            </div>
        </form>
    </div>
{% endblock %}

HW_code/RPI/flaskapp/templates/signup.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
    <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class="formwrapper">
        <form method="POST">
            {{ form.csrf_token() }}

            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}

            <fieldset class="name">
                {{ form.name.label }}
                {{ form.name(placeholder='Name Surname') }}
                {% if form.name.errors %}
                    <ul class="errors">
                        {% for error in form.name.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="email">
                {{ form.email.label }}
                {{ form.email(placeholder='youremail@example.com') }}
                {% if form.email.errors %}
                    <ul class="errors">
                        {% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="password">
                {{ form.password.label }}
                {{ form.password }}
                {% if form.password.errors %}
                    <ul class="errors">
                        {% for error in form.password.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="confirm">
                {{ form.confirm.label }}
                {{ form.confirm }}
                {% if form.confirm.errors %}
                    <ul class="errors">
                        {% for error in form.confirm.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="device">
                {{ form.device.label }}
                {{ form.device }}
                {% if form.device.errors %}
                    <ul class="errors">
                        {% for error in form.device.errors %}<li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <div class="submitbutton">
                <input id="submit" type="submit" value="Create Account"> 
            </div>


        </form>

        <div class="loginsignup">
            <span>Already registered this node? <a href="{{ url_for('auth_bp.login') }}">Log in.</a></span>
        </div>
    </div>
{% endblock %}